export type DeviceStatus = {
  readonly out0: boolean;
  readonly out1: boolean;
  readonly out2: boolean;
  readonly out3: boolean;
  readonly out4: boolean;
  readonly out5: boolean;
  readonly di0: string;
  readonly di1: string;
  readonly di2: string;
  readonly di3: string;
  readonly ia0: number;
  readonly ia1: number;
  readonly ia2: number;
  readonly ia3: number;
  readonly ia4: number;
  readonly ia5: number;
  readonly ia6: number;
  readonly ia7: number;
  readonly ia8: number;
  readonly ia9: number;
  readonly ia10: number;
  readonly ia11: number;
  readonly ia12: number;
  readonly ia13: number;
  readonly ia14: number;
  readonly ia15: number;
  readonly ia16: number;
  readonly ia17: number;
  readonly ia18: number;
  readonly ia19: number;
  readonly sec0: number;
  readonly sec1: number;
  readonly sec2: number;
  readonly sec3: number;
  readonly sec4: number;
  readonly freq: number;
  readonly duty: number;
  readonly pwm: number;
};

export type DeviceStatusValues = keyof DeviceStatus;
